name: android-build-validation

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEPLOY_ENV: staging

jobs:
  build:
    runs-on:
      group: Blipin-Vendor
      labels: [ self-hosted ]
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}

      - name: Flutter pub get
        run: flutter pub get

      - name: Setup Firebase
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$FIREBASE_CREDENTIALS_JSON" | base64 --decode > firebase_credentials.json
          echo "$FIREBASE_OPTIONS_DART" | base64 --decode > lib/firebase_options_${{ env.DEPLOY_ENV }}.dart        
          mkdir -p android/app/src/${{ env.DEPLOY_ENV }}
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/src/${{ env.DEPLOY_ENV }}/google-services.json
          echo "$FIREBASE_JSON" | base64 --decode > firebase.json
#
#      - name: Setup Map Api Key
#        env:
#          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
#        run: |
#          echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" > secrets.properties

      - name: Setup Android Keystore
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/keystores/android_keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_VALIDATION_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_VALIDATION_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_VALIDATION_KEY_PASSWORD }}
        run: |
          mkdir -p keystores
          echo "${{ secrets.ANDROID_VALIDATION_KEYSTORE_JKS }}" | base64 --decode > ${{ env.ANDROID_KEYSTORE_PATH }}
          cat <<EOF > keystores/key.properties
          storeFile=${{ env.ANDROID_KEYSTORE_PATH }}
          storePassword=${{ env.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ env.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ env.ANDROID_KEY_ALIAS }}
          EOF

      - name: Install Fastlane
        run: bundle install

      - name: Run Fastlane lane (APK build + Firebase upload)
        run: bundle exec fastlane staging_validation_apk
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CREDENTIALS_JSON_PATH: ${{ github.workspace }}/firebase_credentials.json
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          FIREBASE_APP_DISTRIBUTION_INTERNAL_TESTER_INVITATION_LINK: ${{ secrets.FIREBASE_APP_DISTRIBUTION_INTERNAL_TESTER_INVITATION_LINK }}
