name: android-build-validation

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEPLOY_ENV: staging

jobs:
  build:
    runs-on:
      group: Blipin-Vendor
      labels: [self-hosted]

    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}

      - name: Flutter Pub Get
        run: |
          flutter clean
          flutter pub get

      - name: Setup Firebase
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$FIREBASE_CREDENTIALS_JSON" | base64 --decode > firebase_credentials.json
          echo "$FIREBASE_OPTIONS_DART" | base64 --decode > lib/firebase_options_${DEPLOY_ENV}.dart

          mkdir -p android/app/src/${DEPLOY_ENV}
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/src/${DEPLOY_ENV}/google-services.json

          echo "$FIREBASE_JSON" | base64 --decode > firebase.json

      - name: Setup Android Keystore
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_VALIDATION_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_VALIDATION_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_VALIDATION_KEY_PASSWORD }}
        run: |
          mkdir -p android/keystores

          echo "${{ secrets.ANDROID_VALIDATION_KEYSTORE_JKS }}" \
            | base64 --decode \
            > android/keystores/android_keystore.jks

          cat <<EOF > android/keystores/key.properties
          storeFile=keystores/android_keystore.jks
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          keyPassword=$ANDROID_KEY_PASSWORD
          EOF

      - name: Build Flutter APK
        run: |
          flutter build apk \
            --flavor $DEPLOY_ENV \
            --release \
            -t lib/main_${DEPLOY_ENV}.dart

      - name: Verify APK
        run: |
          find build -name "*.apk"

      - name: Install Fastlane
        working-directory: android
        run: |
          gem install bundler
          bundle install

      - name: Upload to Firebase
        working-directory: android
        run: bundle exec fastlane upload_validation
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CREDENTIALS_JSON_PATH: ${{ github.workspace }}/firebase_credentials.json
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          FIREBASE_APP_DISTRIBUTION_INTERNAL_TESTER_INVITATION_LINK: ${{ secrets.FIREBASE_APP_DISTRIBUTION_INTERNAL_TESTER_INVITATION_LINK }}