name: ios-build-validation

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Validate Compilability and Unit Tests
    runs-on:
      group: Blipin-Client
      labels: [ self-hosted, macOS ] # Note: iOS builds require a macOS host machine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Run Unit Tests
        run: flutter test

      - name: Build iOS App (Validation)
        run: flutter build ios --no-codesign --debug